-- soft delete for users
alter table users
add column if not exists is_active boolean not null default true;

alter table users
add column if not exists deleted_at timestamptz;


-- saved floor plan versions
create table if not exists floor_plan_versions (
  version_id bigint generated by default as identity primary key,
  floor_plan_id bigint not null,
  plan_data jsonb not null,
  created_at timestamptz not null default now()
);


-- foreign key to floor_plans
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'floor_plan_versions_floor_plan_id_fkey'
  ) then
    alter table floor_plan_versions
    add constraint floor_plan_versions_floor_plan_id_fkey
    foreign key (floor_plan_id)
    references floor_plans(id)
    on delete cascade;
  end if;
end $$;


-- index for faster version history loading
create index if not exists floor_plan_versions_floor_plan_id_created_at_idx
on floor_plan_versions (floor_plan_id, created_at);


-- superadmin role
insert into roles (name)
select 'superadmin'
where not exists (
  select 1 from roles where name = 'superadmin'
);